export const mockProperties = [
  {
    id: 'p1',
    propertyName: 'Greenwood Student Apartments',
    location: 'Coventry City Centre',
    address: 'Greenwood Student Apartments, Coventry City Centre, UK',
    currency: 'GBP',
    price: 450,
    rent: 450,
    commuteTime: 18,
    countryCode: 'GB',
    lat: 52.4080,
    lng: -1.5090,
    environmentType: 'quiet',
    smokingPolicy: 'not allowed',
    guestPolicy: 'restricted',
    studyEnvironment: 'study-friendly',
    cleaningExpectation: 'strict',
    quietHours: 'late night',
    sharedSpaces: ['Kitchen', 'Study Room', 'Gym'],
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=600',
    tags: ['Quiet', 'Library Access'],
    lifestyleTags: ['quiet_household', 'study_focused', 'clean_organized'],
    lifestyleVector: [4, 5, 1, 5, 1]
  },
  {
    id: 'p2',
    propertyName: 'Earlsdon Heights',
    location: 'Earlsdon, Coventry',
    address: 'Earlsdon Heights, Earlsdon, Coventry, UK',
    currency: 'GBP',
    price: 380,
    rent: 380,
    commuteTime: 24,
    countryCode: 'GB',
    lat: 52.4010,
    lng: -1.5350,
    environmentType: 'social',
    smokingPolicy: 'allowed',
    guestPolicy: 'flexible',
    studyEnvironment: 'normal',
    cleaningExpectation: 'moderate',
    quietHours: 'none',
    sharedSpaces: ['Lounge', 'Garden'],
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1de2d93688?auto=format&fit=crop&q=80&w=600',
    tags: ['Social', 'Student Hub'],
    lifestyleTags: ['social_friendly', 'shared_activities', 'guest_friendly'],
    lifestyleVector: [2, 3, 5, 3, 4]
  },
  {
    id: 'p3',
    propertyName: 'Canley Riverside',
    location: 'Canley, Coventry',
    address: 'Canley Riverside, Canley, Coventry, UK',
    currency: 'GBP',
    price: 520,
    rent: 520,
    commuteTime: 16,
    countryCode: 'GB',
    lat: 52.3920,
    lng: -1.5620,
    environmentType: 'quiet',
    smokingPolicy: 'not allowed',
    guestPolicy: 'flexible',
    studyEnvironment: 'study-friendly',
    cleaningExpectation: 'moderate',
    quietHours: 'evening',
    sharedSpaces: ['Private Study Cubicles', 'Kitchen'],
    imageUrl: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=600',
    tags: ['Quiet', 'Near Campus'],
    lifestyleTags: ['quiet_household', 'early_sleep'],
    lifestyleVector: [4, 3, 2, 5, 2]
  },
  {
    id: 'p4',
    propertyName: 'The Tower Residences',
    location: 'Coventry Business District',
    address: 'The Tower Residences, Coventry Business District, UK',
    currency: 'GBP',
    price: 650,
    rent: 650,
    commuteTime: 13,
    countryCode: 'GB',
    lat: 52.4100,
    lng: -1.5120,
    environmentType: 'social',
    smokingPolicy: 'not allowed',
    guestPolicy: 'restricted',
    studyEnvironment: 'study-friendly',
    cleaningExpectation: 'strict',
    quietHours: 'late night',
    sharedSpaces: ['Rooftop', 'Gym', 'Cinema Room'],
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=600',
    tags: ['Luxury', 'Modern'],
    lifestyleTags: ['clean_organized', 'study_focused', 'non_smoking'],
    lifestyleVector: [3, 5, 3, 5, 2]
  },
  {
    id: 'p5',
    propertyName: 'Hearsall Lane Shared House',
    location: 'Hearsall Common',
    address: 'Hearsall Lane Shared House, Hearsall Common, Coventry, UK',
    currency: 'GBP',
    price: 350,
    rent: 350,
    commuteTime: 28,
    countryCode: 'GB',
    lat: 52.4030,
    lng: -1.5420,
    environmentType: 'social',
    smokingPolicy: 'allowed',
    guestPolicy: 'flexible',
    studyEnvironment: 'normal',
    cleaningExpectation: 'flexible',
    quietHours: 'none',
    sharedSpaces: ['Backyard', 'Kitchen'],
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600',
    tags: ['Affordable', 'Social'],
    lifestyleTags: ['music_friendly', 'pet_friendly', 'social_friendly'],
    lifestyleVector: [2, 2, 5, 2, 5]
  }
];

export const mockCampuses = [
  {
    id: 'c1',
    name: 'University of Leicester (le.ac.uk)',
    lat: 52.6212,
    lng: -1.1248,
  },
  {
    id: 'c2',
    name: 'Coventry University (coventry.ac.uk)',
    lat: 52.4059,
    lng: -1.4992,
  },
  {
    id: 'c3',
    name: 'De Montfort University (dmu.ac.uk)',
    lat: 52.6298,
    lng: -1.1396,
  },
  {
    id: 'c4',
    name: 'University of Warwick (warwick.ac.uk)',
    lat: 52.3793,
    lng: -1.5615,
  },
  {
    id: 'c5',
    name: 'Loughborough University (lboro.ac.uk)',
    lat: 52.765,
    lng: -1.224,
  },
  {
    id: 'c6',
    name: 'University of Birmingham (birmingham.ac.uk)',
    lat: 52.4508,
    lng: -1.9305,
  },
  {
    id: 'c7',
    name: 'Nottingham Trent University (ntu.ac.uk)',
    lat: 52.9569,
    lng: -1.1512,
  },
];

/** @param {string | undefined} campusId */
export function getCampusById(campusId) {
  const found = mockCampuses.find((c) => c.id === campusId);
  return found || mockCampuses[0];
}

export const mockUserPreferences = {
  wakeUpTime: 'early',
  sleepTime: 'before 10pm',
  cleanliness: 'very clean',
  noisePreference: 'quiet',
  studyTime: 'night',
  socialLevel: 'rarely invite friends',
  smoking: 'non-smoker',
  drinking: 'never',
  guestPreference: 'never',
  preferredCampusId: 'c1'
};

